export declare const EMPTY_FUNCTION: () => void;
export declare const EMPTY_ARRAY: never[];
export declare const EMPTY_OBJECT: {};
export declare const EMPTY_COMPONENT: () => null;
export declare const END_POINT = "/api";
export declare const WS_URI: string;
export declare const CUSTOMIZE = "__customize__";
export declare const MAX_VOL_SIZE: number;
export declare const AUTO_SCHEDULE = "AUTO_SCHEDULE";
export declare const DAYJS_I18N_MAP: Record<string, string>;
export declare const NO_FOLDER = "NO_FOLDER";
export declare const NO_DATACENTER = "NO_DATACENTER";
export declare const DEFAULT_STORAGE_POLICY_UUID = "dce52578-3824-4b34-97a2-af09950bb0ac";
export declare const WINDOWS = "WINDOWS";
export declare const LINUX = "LINUX";
