---
schema: "../../../tower/packages/server/src/generated/schema.graphql"
documents:
- "../../../tower/packages/ui/src/generated/query.graphql"
- "../../../tower/packages/ui/src/generated/global-search.graphql"
- "../../../tower/packages/ui/src/generated/fetch-by-ids.graphql"
- "../../../tower/packages/ui/src/graphql/*.graphql"
generates:
  src/generated/react-hooks.ts:
    plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
    config:
      scalars:
        DateTime: string
        JSON: "{ [key: string]: any }"
      withComponent: false
      withHOC: false
      withHooks: true
      maybeValue: T | null | undefined
  src/generated/global-search.ts:
    plugins:
    - "../claw/dist/typescript/global-search.js"
  src/generated/images-type.ts:
    plugins:
    - "../claw/dist/typescript/images-type.js"
config:
  path: src/codegen/config/codegen-config.json
  imagesPath: src/images
