import { Actions as BackupSearchActionType, BackupSearchState } from "./backup";
import { Actions as ChartActionType, ChartState } from "./chart";
import { Actions as EverouteActionType, EverouteState } from "./everoute";
import { Actions as GlobalSearchActionType, GlobalSearchState } from "./globalSearch";
import { Actions as ModalActionType, CloseCb, ModalProps, ModalState, ModalType } from "./modal";
import { Actions as NavActionType, NavState } from "./nav";
import { Actions as TableActionType, TableState } from "./table";
import { Actions as TaskActionType, TaskState } from "./task";
import { Actions as UploadActionType, UploadState } from "./upload";
export { BackupSearchActions } from "./backup";
export { ChartActions } from "./chart";
export { EverouteActions } from "./everoute";
export { GloablSearchActions } from "./globalSearch";
export { ModalActions } from "./modal";
export { NavActions } from "./nav";
export { TableActions } from "./table";
export { TaskActions } from "./task";
export { UploadActions } from "./upload";
export declare type RootState = {
    chart: ChartState;
    modal: ModalState;
    upload: UploadState;
    table: TableState;
    task: TaskState;
    globalSearch: GlobalSearchState;
    nav: NavState;
    everoute: EverouteState;
    backupSearch: BackupSearchState;
};
export declare type Actions = ModalActionType | ChartActionType | UploadActionType | TableActionType | TaskActionType | GlobalSearchActionType | NavActionType | EverouteActionType | BackupSearchActionType | {
    type: "RESET";
};
export declare const rootReducer: (state: RootState | undefined, action: Actions) => import("redux").CombinedState<{
    chart: ChartState;
    modal: ModalState;
    upload: UploadState;
    table: TableState;
    task: TaskState;
    globalSearch: GlobalSearchState;
    nav: NavState;
    everoute: EverouteState;
    backupSearch: BackupSearchState;
}>;
export declare const store: import("redux").Store<import("redux").EmptyObject & {
    chart: ChartState;
    modal: ModalState;
    upload: UploadState;
    table: TableState;
    task: TaskState;
    globalSearch: GlobalSearchState;
    nav: NavState;
    everoute: EverouteState;
    backupSearch: BackupSearchState;
}, Actions>;
export declare function pushModal<K extends keyof ModalProps>(modal: ModalType<ModalProps[K]>): void;
export declare function popModal(): void;
export declare function closeModal(id: number): void;
export declare type GetModalProps<K extends keyof ModalProps> = ModalProps[K] & CloseCb;
export * from "./backup";
export * from "./chart";
export * from "./everoute";
export * from "./globalSearch";
export * from "./modal";
export * from "./nav";
export * from "./table";
export * from "./task";
export * from "./upload";
