/**
 * This file is generated by the ejs template,
 * Please do not modify this file directly to
 * avoid being overwritten by the automatic generation process.
 * Take look as packages/eagle/tools/genHtmlEvent.mts.
 */
import { fireEvent, render, screen } from "@testing-library/react";
import React, { PropsWithChildren, useContext } from "react";
import { describe, expect, it, vi } from "vitest";

import { kitContext } from "../../../spec";
import { antdKit } from "../../antd";
import KitStoreProvider from "../../KitStoreProvider";
import ModalStack from "../../ModalStack";

const AllTheProviders = ({ children }: PropsWithChildren<{}>) => {
  return (
    <KitStoreProvider>
      <kitContext.Provider value={antdKit}>
        <ModalStack />
        {children}
      </kitContext.Provider>
    </KitStoreProvider>
  );
};

const onClick = vi.fn();

const onDoubleClick = vi.fn();

const onMouseEnter = vi.fn();

const Component = () => {
  const kit = useContext(kitContext);

  return (
    <kit.button
      onClick={onClick}
      onDoubleClick={onDoubleClick}
      onMouseEnter={onMouseEnter}
      data-testid="Button"
    />
  );
};

describe("Button htmlEvent", () => {
  it("onClick", () => {
    render(<Component />, {
      wrapper: AllTheProviders,
    });

    fireEvent.click(screen.getByTestId("Button"));

    expect(onClick).toBeCalledTimes(1);
  });

  it("onDoubleClick", () => {
    render(<Component />, {
      wrapper: AllTheProviders,
    });

    fireEvent.doubleClick(screen.getByTestId("Button"));

    expect(onDoubleClick).toBeCalledTimes(1);
  });

  it("onMouseEnter", () => {
    render(<Component />, {
      wrapper: AllTheProviders,
    });

    fireEvent.mouseEnter(screen.getByTestId("Button"));

    expect(onMouseEnter).toBeCalledTimes(1);
  });
});
