/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Tuna {
  responses: {
    getBricks: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Disk layout
         */
        brick_disk_layout?: {
          /**
           * Slot count
           */
          column?: number;
          /**
           * Disk orientation
           */
          direct?: "H" | "V";
          /**
           * Disk location
           */
          phase?: "U" | "D" | "F" | "B" | "L" | "R";
          /**
           * Row count of disk slots
           */
          row?: number;
        }[];
        /**
         * Brick model
         */
        brick_model?: string;
        /**
         * Brick name
         */
        brick_name?: string;
        power?: {
          /**
           * Power layout
           */
          power_layout?: "V" | "H";
          power_pos?: "M" | "R";
          power_status?: {
            /**
             * This interface was referenced by `undefined`'s JSON-Schema definition
             * via the `patternProperty` "^\d+$".
             */
            [k: string]: {
              id?: string;
              msg?: string;
              /**
               * Power state
               */
              status?: boolean;
            };
          };
        };
        /**
         * Topo ID
         */
        topo_id?: string;
        /**
         * Tag position for node
         */
        tag_position_in_brick?: {
          column?: number;
          row?: number;
          tag?: string;
        }[];
      }[];
    };
    clusterSoftwareInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Virtualization platform
         */
        hypervisor?: string;
        /**
         * Current version
         */
        latest_version?: string;
        /**
         * Enable vhost or not
         */
        vhost_enabled?: boolean;
        /**
         * Enable pmem or not
         */
        pmem_enabled?: boolean;
        /**
         * Enable nvmf rdma or not
         */
        nvme_over_rdma_enabled?: boolean;
        /**
         * Enable nvmf tcp or not
         */
        nvme_over_tcp_enabled?: boolean;
      };
    };
    clusterHardwareInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * platform architecture
         */
        arch?: string;
      };
    };
    clusterStorageInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Cluster name
         */
        cluster_name?: string;
        /**
         * Cluster UUID
         */
        cluster_uuid?: string;
        /**
         * Cluster dirty cache space
         */
        dirty_cache_space?: number;
        /**
         * Cluster invalid cache space
         */
        failure_cache_space?: number;
        /**
         * Cluster invalid storage space
         */
        failure_data_space?: number;
        hosts?: {
          data?: {
            /**
             * Cache space
             */
            cache_space?: number;
            /**
             * Node space
             */
            chunk_space?: number;
            /**
             * Data space
             */
            data_space?: number;
            /**
             * Dirty cache space
             */
            dirty_cache_space?: number;
            /**
             * Invalid cache space
             */
            failure_cache_space?: number;
            /**
             * Invalid data space
             */
            failure_data_space?: number;
            /**
             * Physical space
             */
            physical_space?: number;
            /**
             * Used data space
             */
            used_data_space?: number;
            /**
             * Invalid cache space
             */
            valid_cache_space?: number;
            /**
             * Invalid data space
             */
            valid_data_space?: number;
          };
          ec?: "EOK";
          /**
           * Node UUID
           */
          host?: string;
          /**
           * Node management IP
           */
          management_ip?: string;
        }[];
        /**
         * Whether this is a stretched cluster
         */
        is_stretched?: boolean;
        /**
         * Space for data to be migrated
         */
        migrate_space?: number;
        /**
         * Preferred availability zone
         */
        preferred_zone_id?: string;
        /**
         * Provisioned space
         */
        provisioned_data_space?: number;
        /**
         * Space for data to be recovered
         */
        recover_space?: number;
        recycle_space?: number;
        /**
         * Cluster cache space
         */
        total_cache_capacity?: number;
        /**
         * Cluster data space
         */
        total_data_capacity?: number;
        /**
         * Used cache space
         */
        used_cache_space?: number;
        /**
         * Used data space
         */
        used_data_space?: number;
        /**
         * Invalid cache space
         */
        valid_cache_space?: number;
        /**
         * Invalid data space includes (1) Data space provided to storage by online unhealthy physical disks; (2) Data space provided to storage by nodes whose storage fails; (3) Data space provided to storage by nodes being unmounted.
         */
        valid_data_space?: number;
        zone_info?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[\w-]+$".
           */
          [k: string]: {
            /**
             * Cluster dirty cache space
             */
            dirty_cache_space?: number;
            /**
             * Cluster invalid cache space
             */
            failure_cache_space?: number;
            /**
             * Cluster invalid storage space
             */
            failure_data_space?: number;
            /**
             * Provisioned space
             */
            provisioned_data_space?: number;
            /**
             * Cluster cache space
             */
            total_cache_capacity?: number;
            /**
             * Cluster data space
             */
            total_data_capacity?: number;
            /**
             * Used cache space
             */
            used_cache_space?: number;
            /**
             * Used data space
             */
            used_data_space?: number;
            /**
             * Invalid cache space
             */
            valid_cache_space?: number;
            /**
             * Invalid data space includes (1) Data space provided to storage by online unhealthy physical disks; (2) Data space provided to storage by nodes whose storage fails; (3) Data space provided to storage by nodes being unmounted.
             */
            valid_data_space?: number;
          };
        };
      };
    };
    getMetroXInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Whether this is a stretched cluster
         */
        is_stretched?: boolean;
        /**
         * Preferred availability zone ID
         */
        preferred_zone_id?: string;
        /**
         * Witness node IP
         */
        witness_ip?: string;
        zones?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[\w-]+$".
           */
          [k: string]: {
            hosts?: {
              /**
               * Node management IP
               */
              data_ip?: string;
              /**
               * Node UUID
               */
              host_uuid?: string;
              [k: string]: any;
            }[];
            /**
             * Availability zone ID
             */
            id?: string;
            /**
             * Availability zone name
             */
            name?: string;
            /**
             * Gateway IP from witness to zone
             */
            from_witness_gateway?: string;
            /**
             * Gateway IP from zone to witness
             */
            to_witness_gateway?: string;
          };
        };
      };
    };
    getClusterMigrationCapabilities: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Whether the cluster support auto converge
         */
        auto_converge?: boolean;
      };
    };
    updateClusterMigrationCapabilities: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    getWitnessInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Hostname of the witness node
         */
        name?: string;
        /**
         * Witness node IP
         */
        data_ip?: string;
        /**
         * Witness node UUID
         */
        host_uuid?: string;
        sys_path?: {
          os?: {
            /**
             * Total space of root partition
             */
            total?: number;
            /**
             * Used space of root partition
             */
            used?: number;
          };
        };
        /**
         * Access network IP
         */
        access_ip?: string;
        /**
         * Brick topo ID
         */
        brick_topo_id?: string;
        cpu?: {
          /**
           * Brief CPU info
           */
          brand?: string;
          /**
           * Supported instruction set
           */
          flags?: string;
          /**
           * CPU frequency
           */
          hz_advertised?: string;
          /**
           * CPU frequency in Hertz
           */
          hz_advertised_raw?: number[];
          /**
           * Core count
           */
          num_cores?: number;
        };
        cvm_resources?: {
          /**
           * CPU core count
           */
          cpus?: number;
          /**
           * Hostname
           */
          hostname?: string;
          /**
           * Memory size
           */
          memory?: number;
        };
        disks?: {
          /**
           * Disk temperature
           */
          celsius_temperature?: string;
          /**
           * Disk's controller
           */
          controller?: string;
          /**
           * Disk firmware version
           */
          firmware?: string;
          /**
           * Disk ID
           */
          id?: string;
          /**
           * Disk health state
           */
          is_healthy?: boolean;
          /**
           * Disk mount state
           */
          is_mounted?: boolean;
          /**
           * Whether the disk is offline
           */
          is_offline?: boolean;
          /**
           * Whether this is a system disk
           */
          is_os_disk?: boolean;
          /**
           * Disk health state
           */
          is_physical_healthy?: boolean;
          /**
           * Whether this is an HDD
           */
          is_rotational?: boolean;
          /**
           * Disk model
           */
          model?: string;
          /**
           * Disk mount state
           */
          mount_status?: string;
          /**
           * Disk drive name
           */
          name?: string;
          /**
           * Disk IO error count
           */
          num_io_errors?: number;
          partitions?: {
            /**
             * Partition name
             */
            name?: string;
            /**
             * Partition label
             */
            path?: string;
            /**
             * Partition size
             */
            size?: number;
            /**
             * Partition use
             */
            usage?: string;
            /**
             * Partition used size
             */
            used_size?: number;
          }[];
          /**
           * Disk label
           */
          path?: string;
          /**
           * Disk serial number
           */
          serial?: string;
          /**
           * Disk capacity
           */
          size?: number;
          /**
           * Whether the disk is in an abnormal state
           */
          staging?: boolean;
          /**
           * Disk type
           */
          type?: "HDD" | "SSD";
        }[];
        /**
         * Service state
         */
        services?: {
          /**
           * pid
           */
          current_pid?: number;
          /**
           * Execution path
           */
          exec_path?: string;
          /**
           * Last pid
           */
          last_pid?: number;
          pinfo?: {
            /**
             * Whether the service is running
             */
            is_running?: boolean;
            /**
             * Process name
             */
            name?: string;
            /**
             * Process state
             */
            status?: string;
            /**
             * Uptime
             */
            uptime?: number;
            /**
             * User who runs this process
             */
            user?: string;
            /**
             * Role of this process
             */
            role?: string;
          };
          /**
           * Running state
           */
          running_state?: string;
          /**
           * Service name
           */
          service_name?: string;
          /**
           * Whether this service is auto-started
           */
          service_state?: string;
          /**
           * Duration since last state change. Unit second.
           */
          state_duration?: number;
        }[];
        elf_nested_kvm?: boolean;
        /**
         * IPMI IP address
         */
        ipmi_ip?: string;
        memory?: {
          /**
           * Memory size
           */
          total?: number;
        };
        /**
         * Node model
         */
        model?: string;
        nics?: {
          /**
           * Bonding info
           */
          bonding_detail?: string;
          /**
           * Not in use for now
           */
          bonding_master?: string;
          /**
           * Bonding mode
           */
          bonding_mode?: string;
          /**
           * Gateway
           */
          gateway?: string;
          /**
           * MAC address
           */
          hwaddr?: string;
          /**
           * IP address
           */
          ipaddr?: string;
          /**
           * Whether this is a physical NIC
           */
          is_physical?: boolean;
          /**
           * MTU
           */
          mtu?: number;
          /**
           * Name
           */
          name?: string;
          /**
           * Mask
           */
          netmask?: string;
          /**
           * Whether it is running
           */
          running?: boolean;
          /**
           * Speed
           */
          speed?: number;
          /**
           * Whether the NIC is up
           */
          up?: boolean;
          /**
           * VLAN ID
           */
          vlan?: string;
          /**
           * Use
           */
          usage?: string;
        }[];
        /**
         * Node role
         */
        role?: string;
        summary?: {
          disks?: {
            hdd?: {
              mounted?: {
                /**
                 * Capacity
                 */
                size?: number;
                /**
                 * Count
                 */
                total?: number;
              };
              not_mounted?: {
                size?: number;
                total?: number;
              };
              unhealthy?: {
                total?: number;
              };
            };
            ssd?: {
              mounted?: {
                /**
                 * Capacity
                 */
                size?: number;
                /**
                 * Count
                 */
                total?: number;
              };
              not_mounted?: {
                size?: number;
                total?: number;
              };
              unhealthy?: {
                total?: number;
              };
            };
            total_size?: number;
          };
        };
        /**
         * Node label
         */
        tags?: string;
        /**
         * Management IP
         */
        management_ip?: string;
        cvm_resource?: {
          /**
           * CPU core count
           */
          cpus?: number;
          /**
           * Hostname
           */
          hostname?: string;
          /**
           * Memory size
           */
          memory?: number;
        };
      };
    };
    getClusterNodesSummary: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    getComputeSummary: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        host_cpu_info?: (string | number)[];
        /**
         * Cluster total CPUs (in Hertz)
         */
        hz?: number;
        /**
         * Count of CPUs already provisioned in cluster
         */
        provisioned_cpu_cores?: number;
        provisioned_cpu_cores_for_active_vm?: number;
        reserved_cpu_cores_for_system_service?: number;
        /**
         * Provisioned memory space in cluster
         */
        provisioned_memory?: number;
        /**
         * Provisioned memory space (in byte) in cluster
         */
        provisioned_memory_in_byte?: number;
        /**
         * Cluster total CPU core count
         */
        total_cpu_cores?: number;
        /**
         * Cluster total memory space
         */
        total_memory?: number;
        /**
         * Cluster total memory space (in byte)
         */
        total_memory_in_byte?: number;
        /**
         * Cluster total VM count
         */
        total_vms?: number;
        /**
         * Used memory space in cluster
         */
        used_memory?: number;
        /**
         * Used memory space (in byte) in cluster
         */
        used_memory_in_byte?: number;
        vms_state?: {
          /**
           * Count of powered-off VMs
           */
          poweredOff?: number;
          /**
           * Count of powered-on VMs
           */
          poweredOn?: number;
          /**
           * Count of suspended VMs
           */
          suspended?: number;
        };
        zone_summary?: {
          /**
           * This interface was referenced by `undefined`'s JSON-Schema definition
           * via the `patternProperty` "^[\w-]+$".
           */
          [k: string]: {
            /**
             * Cluster total CPUs (in Hertz)
             */
            hz?: number;
            /**
             * Count of CPUs already provisioned in cluster
             */
            provisioned_cpu_cores?: number;
            provisioned_cpu_cores_for_active_vm?: number;
            /**
             * Provisioned memory space in cluster
             */
            provisioned_memory?: number;
            /**
             * Provisioned memory space (in byte) in cluster
             */
            provisioned_memory_in_byte?: number;
            /**
             * Cluster total CPU core count
             */
            total_cpu_cores?: number;
            /**
             * Cluster total memory space
             */
            total_memory?: number;
            /**
             * Cluster total memory space (in byte)
             */
            total_memory_in_byte?: number;
            /**
             * Cluster total VM count
             */
            total_vms?: number;
            /**
             * Used memory space in cluster
             */
            used_memory?: number;
            /**
             * Used memory space (in byte) in cluster
             */
            used_memory_in_byte?: number;
            vms_state?: {
              /**
               * Count of powered-off VMs
               */
              poweredOff?: number;
              /**
               * Count of powered-on VMs
               */
              poweredOn?: number;
              /**
               * Count of suspended VMs
               */
              suspended?: number;
              [k: string]: any;
            };
          };
        };
      };
    };
    uploadISO: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    uploadMetadata: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    mergeISO: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    storeISO: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    deleteISO: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    getMetadataList: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        metadata_name?: {
          /**
           * Whether it is a general release
           */
          is_release_version?: boolean;
          /**
           * md5 value
           */
          md5?: string;
          /**
           * Metadata name
           */
          name?: string;
          /**
           * Whether upgrade of kernel is needed
           */
          need_kernel_upgrade?: boolean;
          /**
           * Whether upgrade of third-party software is needed
           */
          need_third_party_rpm_upgrade?: boolean;
          /**
           * Release date
           */
          release_data?: number;
          /**
           * ISO size
           */
          size?: number;
          /**
           * SMTX OS version
           */
          smtx_version?: string;
          upgrade_from?: string[];
          upgrade_tool_version?: {
            [k: string]: any;
          };
          rpms?: {
            /**
             * rpm name
             */
            name?: string;
            /**
             * rpm version
             */
            version?: string;
          }[];
        };
      };
    };
    preCheck: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    upgrade: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        data?: {
          /**
           * ID
           */
          _id?: string;
          /**
           * Time when upgrade ends
           */
          end_time?: string;
          /**
           * Failure info
           */
          failed_message?: string;
          pre_upgrade_progress?: string;
          /**
           * IP of the node controlling upgrade
           */
          running_node_ip?: string;
          /**
           * Source ISO version
           */
          src_iso_version?: string;
          /**
           * Time when upgrade starts
           */
          start_timestamp?: string;
          /**
           * Upgrade state
           */
          status?: "running" | "success" | "failed";
          /**
           * Target ISO file
           */
          target_iso_file?: string;
          /**
           * Target metadata file
           */
          target_iso_metadata_file?: string;
          upgrade_node_ips?: string[];
          upgrade_progress?: {
            /**
             * Current step
             */
            current_step?: number;
            /**
             * Current state
             */
            progress?: number;
            stage?: string;
            /**
             * Total upgrade steps
             */
            total_step?: number;
            node_progress?: {
              /**
               * Current step
               */
              current_step?: number;
              finished_stage?: string[];
              /**
               * Node IP
               */
              node_ip?: string;
              /**
               * Upgrade progress
               */
              progress?: number;
              stage?: string;
              /**
               * Total upgrade steps
               */
              total_step?: number;
            }[];
          };
        };
      };
    };
    getProgress: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        data?: {
          /**
           * ID
           */
          _id?: string;
          /**
           * Time when upgrade ends
           */
          end_time?: string;
          /**
           * Failure info
           */
          failed_message?: string;
          pre_upgrade_progress?: string;
          /**
           * IP of the node controlling upgrade
           */
          running_node_ip?: string;
          /**
           * Source ISO version
           */
          src_iso_version?: string;
          /**
           * Time when upgrade starts
           */
          start_timestamp?: string;
          /**
           * Upgrade state
           */
          status?: "running" | "success" | "failed";
          /**
           * Target ISO file
           */
          target_iso_file?: string;
          /**
           * Target metadata file
           */
          target_iso_metadata_file?: string;
          upgrade_node_ips?: string[];
          upgrade_progress?: {
            /**
             * Current step
             */
            current_step?: number;
            /**
             * Current state
             */
            progress?: number;
            stage?: string;
            /**
             * Total upgrade steps
             */
            total_step?: number;
            node_progress?: {
              /**
               * Current step
               */
              current_step?: number;
              finished_stage?: string[];
              /**
               * Node IP
               */
              node_ip?: string;
              /**
               * Upgrade progress
               */
              progress?: number;
              stage?: string;
              /**
               * Total upgrade steps
               */
              total_step?: number;
            }[];
          };
        };
      };
    };
    getHistory: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Upgrade date
         */
        date?: number;
        progress?: {
          data?: {
            /**
             * ID
             */
            _id?: string;
            /**
             * Time when upgrade ends
             */
            end_time?: string;
            /**
             * Failure info
             */
            failed_message?: string;
            pre_upgrade_progress?: string;
            /**
             * IP of the node controlling upgrade
             */
            running_node_ip?: string;
            /**
             * Source ISO version
             */
            src_iso_version?: string;
            /**
             * Time when upgrade starts
             */
            start_timestamp?: string;
            /**
             * Upgrade state
             */
            status?: "running" | "success" | "failed";
            /**
             * Target ISO file
             */
            target_iso_file?: string;
            /**
             * Target metadata file
             */
            target_iso_metadata_file?: string;
            upgrade_node_ips?: string[];
            upgrade_progress?: {
              /**
               * Current step
               */
              current_step?: number;
              /**
               * Current state
               */
              progress?: number;
              stage?: string;
              /**
               * Total upgrade steps
               */
              total_step?: number;
              node_progress?: {
                /**
                 * Current step
                 */
                current_step?: number;
                finished_stage?: string[];
                /**
                 * Node IP
                 */
                node_ip?: string;
                /**
                 * Upgrade progress
                 */
                progress?: number;
                stage?: string;
                /**
                 * Total upgrade steps
                 */
                total_step?: number;
              }[];
            };
          };
        };
        /**
         * Whether the upgrade is successful
         */
        result?: string;
        /**
         * Target version of upgrade
         */
        src_iso_version?: string;
        /**
         * ID of upgrade task
         */
        task_uuid?: string;
        /**
         * Time taken for this upgrade
         */
        used_time?: number;
      }[];
    };
    getNodeUpgradeLog: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: string[];
    };
    MountCacheDisk: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    UmountCacheDisk: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    MountPartitionDisk: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    UmountPartitionDisk: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    TurnOnLed: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: string;
    };
    TurnOffLed: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: string;
    };
    GetSriovInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        uuid?: string;
        name?: string;
        /**
         * sriov info
         */
        sriov?: {
          /**
           * sriov vf number maximum according to hardware
           */
          totalvfs?: number;
          /**
           * total sriov vf number set by user
           */
          numvfs?: number;
          assigned_vfs?: {
            /**
             * sriov vf index
             */
            index?: number;
          }[];
        };
      };
    };
    SetSriovNumvfs: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    getHostsInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Access network IP
         */
        access_ip?: string;
        /**
         * Brick topo ID
         */
        brick_topo_id?: string;
        /**
         * CHUNK ID
         */
        chunk_id?: number;
        cgroup?: {
          /**
           * reserved_cpu_cores_for_system_service
           */
          os_cpu_used?: number;
          /**
           * Real available core, including thread count
           */
          qemu_cpu_used?: number;
        };
        cpu?: {
          /**
           * Brief CPU info
           */
          brand?: string;
          /**
           * Label
           */
          flags?: string;
          /**
           * CPU frequency
           */
          hz_advertised?: string;
          hz_advertised_raw?: number[];
          /**
           * CPU core count
           */
          num_cores?: number;
          sockets?: number;
          /**
           * CPU vendor
           */
          vendor?: string;
          /**
           * CPU architecture
           */
          arch?: string;
        };
        cvm_resource?: {
          /**
           * CPU core count
           */
          cpus?: number;
          /**
           * Hostname
           */
          hostname?: string;
          /**
           * Memory size
           */
          memory?: number;
        };
        /**
         * Node management IP
         */
        data_ip?: string;
        /**
         * Node IPMI IP
         */
        ipmi_ip?: string;
        disks?: {
          /**
           * Disk temperature
           */
          celsius_temperature?: string;
          /**
           * Disk's controller
           */
          controller?: string;
          /**
           * Disk firmware version
           */
          firmware?: string;
          /**
           * Disk ID
           */
          id?: string;
          /**
           * Disk  function
           */
          function?: string;
          /**
           * Disk health state
           */
          is_healthy?: boolean;
          /**
           * Disk mount state
           */
          is_mounted?: boolean;
          /**
           * Whether the disk is offline
           */
          is_offline?: boolean;
          /**
           * Whether this is a system disk
           */
          is_os_disk?: boolean;
          /**
           * Disk health state
           */
          is_physical_healthy?: boolean;
          /**
           * Whether this is an HDD
           */
          is_rotational?: boolean;
          /**
           * Disk model
           */
          model?: string;
          /**
           * Disk mount state
           */
          mount_status?: string;
          /**
           * Disk drive name
           */
          name?: string;
          /**
           * Disk IO error count
           */
          num_io_errors?: number;
          partitions?: {
            /**
             * Partition name
             */
            name?: string;
            /**
             * Partition label
             */
            path?: string;
            /**
             * Partition size
             */
            size?: number;
            /**
             * Partition use
             */
            usage?: string;
            /**
             * Partition used size
             */
            used_size?: number;
          }[];
          /**
           * Disk label
           */
          path?: string;
          /**
           * Disk physical slot on brick
           */
          physical_slot?: string;
          /**
           * Disk serial number
           */
          serial?: string;
          /**
           * Disk capacity
           */
          size?: number;
          /**
           * Whether the disk is in an abnormal state
           */
          staging?: boolean;
          /**
           * Disk type
           */
          type?: "HDD" | "SSD";
          /**
           * Whether the disk is healthy in chunk
           */
          is_healthy_in_chunk?: boolean;
          hints?: {
            chunk_errflag?: boolean;
            chunk_warnflag?: boolean;
            iostat_latency?: boolean;
            smart_check?: boolean;
            chunk_io_error?: boolean;
            chunk_checksum_error?: boolean;
          };
          extra_info?: {
            chunk_num_checksum_errors?: number;
            chunk_num_io_errors?: number;
            rw_await?: number;
            self_assessment_error?: boolean;
            smartctl_hang?: string;
          };
        }[];
        host_state?: {
          maintenance_job_id?: string;
          state?:
            | "in_use"
            | "entering_maintenance_mode"
            | "maintenance_mode"
            | "removing";
          uuid?: string;
        };
        pmems?: {
          regions?: {
            dev?: string;
            iset_id?: string;
            Capacity?: number;
            size?: number;
            numa_node?: number;
            SocketID?: string;
            PersistentMemoryType?: string;
            type?: string;
            HealthState?: string;
            DimmID?: string[];
            is_mounted?: boolean;
            mount_status?: string;
            function?: string;
            is_healthy_in_chunk?: boolean;
            namespaces?: {
              map?: string;
              uuid?: string;
              numa_node?: number;
              dev?: string;
              usage?: string;
              chardev?: string;
              size?: number;
              used_size?: number;
            }[];
          }[];
          dimms?: {
            dev?: string;
            DimmID?: string;
            Capacity?: number;
            SocketID?: string;
            DeviceLocator?: string;
            FWVersion?: string;
            PartNumber?: string;
            HealthState?: string;
            health?: {
              controller_temperature_celsius?: number;
              spares_percentage?: number;
              temperature_celsius?: number;
              health_state?: string;
            };
          }[];
        };
        /**
         * Whether enable nested virtualization
         */
        elf_nested_kvm?: boolean;
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hypervisor IP
         */
        hypervisor_ip?: string;
        /**
         * Time stamp of the last collection of disk info
         */
        last_disk_modified?: string;
        /**
         * Node management IP
         */
        management_ip?: string;
        memory?: {
          /**
           * Node memory size
           */
          total?: number;
        };
        /**
         * Node model
         */
        model?: string;
        /**
         * Time stamp of collection of node info
         */
        modified?: string;
        /**
         * Node name
         */
        name?: string;
        nics?: {
          /**
           * Bonding info
           */
          bonding_detail?: string;
          /**
           * Bonded master NIC
           */
          bonding_master?: string;
          /**
           * Bonding mode
           */
          bonding_mode?: string;
          /**
           * Gateway
           */
          gateway?: string;
          /**
           * MAC address
           */
          hwaddr?: string;
          /**
           * IP address
           */
          ipaddr?: string;
          /**
           * Whether this is a physical NIC
           */
          is_physical?: boolean;
          /**
           * MTU
           */
          mtu?: number;
          /**
           * Name
           */
          name?: string;
          /**
           * Mask
           */
          netmask?: string;
          /**
           * Whether it is running
           */
          running?: boolean;
          /**
           * Speed
           */
          speed?: number;
          /**
           * Whether the NIC is up
           */
          up?: boolean;
          /**
           * VLAN ID
           */
          vlan?: string;
          /**
           * Use
           */
          usage?: string;
          /**
           * nic uuid
           */
          uuid?: string;
          /**
           * nic model
           */
          model?: string;
          /**
           * nic driver type
           */
          driver?: string;
          /**
           * nic driver state
           */
          driver_state?: string;
          /**
           * nic support sriov
           */
          is_sriov_support?: boolean;
          /**
           * sriov info
           */
          sriov?: {
            /**
             * sriov vf number maximum according to hardware
             */
            totalvfs?: number;
            /**
             * total sriov vf number set by user
             */
            numvfs?: number;
            assigned_vfs?: {
              /**
               * sriov vf index
               */
              index?: number;
            }[];
          };
        }[];
        /**
         * Role
         */
        role?: string;
        /**
         * RPC IP (storage IP)
         */
        rpc_ip?: string;
        /**
         * Serial number
         */
        sn?: string;
        /**
         * Node state
         */
        status?: number;
        /**
         * Storage pool ID
         */
        storage_pool_id?: string;
        summary?: {
          disks?: {
            hdd?: {
              mounted?: {
                /**
                 * Capacity
                 */
                size?: number;
                /**
                 * Count
                 */
                total?: number;
              };
              not_mounted?: {
                size?: number;
                total?: number;
              };
              unhealthy?: {
                total?: number;
              };
            };
            ssd?: {
              mounted?: {
                /**
                 * Capacity
                 */
                size?: number;
                /**
                 * Count
                 */
                total?: number;
              };
              not_mounted?: {
                size?: number;
                total?: number;
              };
              unhealthy?: {
                total?: number;
              };
            };
            total_size?: number;
          };
        };
        sys_path?: {
          meta?: {
            /**
             * Total capacity
             */
            total?: number;
            /**
             * Used capacity
             */
            used?: number;
          };
          os?: {
            /**
             * Total capacity
             */
            total?: number;
            /**
             * Used capacity
             */
            used?: number;
          };
          zk?: {
            /**
             * Total capacity
             */
            total?: number;
            /**
             * Used capacity
             */
            used?: number;
          };
        };
        tags?: string[];
        /**
         * Topo ID
         */
        topo_id?: string;
        /**
         * Usage state
         */
        use_state?: number;
        /**
         * Availability zone ID
         */
        zone_id?: string;
        /**
         * Availability zone name
         */
        zone_name?: string;
        with_faster_ssd_as_cache?: boolean;
        is_os_in_raid1?: boolean;
      }[];
    };
    getDiskRecommendedUsage: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: string;
    };
    getHostSummary: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        hdd_size?: number;
        host_cpu_info?: (string | number)[][];
        /**
         * Node frequency in Hertz
         */
        hz?: number;
        /**
         * Node memory size
         */
        memory_size?: number;
        /**
         * Total CPU core count
         */
        num_cores?: number;
        /**
         * Total node count
         */
        num_hosts?: number;
        /**
         * Total SSD capacity
         */
        ssd_size?: number;
        unmounted?: {
          host?: string[];
        };
        zone_summary?: {
          topo_id?: {
            hdd_size?: number;
            host_cpu_info?: string[][];
            hz?: number;
            memory_size?: number;
            num_cores?: number;
            num_hosts?: number;
            ssd_size?: number;
            unmounted?: {
              host?: string[];
            };
          };
        };
      };
    };
    getSpecificIPMIAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node management IP address
         */
        host?: string;
        /**
         * Node IPMI interface
         */
        interface?: string;
        /**
         * Whether the node IPMI account is valid
         */
        is_valid?: boolean;
        /**
         * Node hostname
         */
        node_name?: string;
        /**
         * Node UUID
         */
        node_uuid?: string;
        /**
         * IPMI service port
         */
        port?: number;
        /**
         * IPMI username
         */
        user?: string;
      };
    };
    updateSpecificIPMIAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node management IP address
         */
        host?: string;
        /**
         * Node IPMI interface
         */
        interface?: string;
        /**
         * Whether the node IPMI account is valid
         */
        is_valid?: boolean;
        /**
         * Node hostname
         */
        node_name?: string;
        /**
         * Node UUID
         */
        node_uuid?: string;
        /**
         * IPMI service port
         */
        port?: number;
        /**
         * IPMI username
         */
        user?: string;
      };
    };
    deleteSpecificIPMIAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    };
    getAllIPMIAccounts: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node management IP address
         */
        host?: string;
        /**
         * Node IPMI interface
         */
        interface?: string;
        /**
         * Whether the node IPMI account is valid
         */
        is_valid?: boolean;
        /**
         * Node hostname
         */
        node_name?: string;
        /**
         * Node UUID
         */
        node_uuid?: string;
        /**
         * IPMI service port
         */
        port?: number;
        /**
         * IPMI username
         */
        user?: string;
      }[];
    };
    createAnIPMIAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node management IP address
         */
        host?: string;
        /**
         * Node IPMI interface
         */
        interface?: string;
        /**
         * Whether the node IPMI account is valid
         */
        is_valid?: boolean;
        /**
         * Node hostname
         */
        node_name?: string;
        /**
         * Node UUID
         */
        node_uuid?: string;
        /**
         * IPMI service port
         */
        port?: number;
        /**
         * IPMI username
         */
        user?: string;
      };
    };
    batchUpsertIPMIAccounts: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        success?: {
          /**
           * Node management IP address
           */
          host?: string;
          /**
           * Node IPMI interface
           */
          interface?: string;
          /**
           * Whether the node IPMI account is valid
           */
          is_valid?: boolean;
          /**
           * Node hostname
           */
          node_name?: string;
          /**
           * Node UUID
           */
          node_uuid?: string;
          /**
           * IPMI service port
           */
          port?: number;
          /**
           * IPMI username
           */
          user?: string;
        }[];
        failure?: {
          /**
           * Node management IP address
           */
          host?: string;
          /**
           * Node IPMI interface
           */
          interface?: string;
          /**
           * Whether the node IPMI account is valid
           */
          is_valid?: boolean;
          /**
           * Node hostname
           */
          node_name?: string;
          /**
           * Node UUID
           */
          node_uuid?: string;
          /**
           * IPMI service port
           */
          port?: number;
          /**
           * IPMI username
           */
          user?: string;
        }[];
      };
    };
    getLogList: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * End time of collection
         */
        collect_end_timestamp?: string;
        /**
         * Start time of collection
         */
        collect_start_timestamp?: string;
        /**
         * End time of a log
         */
        end_timestamp?: string;
        node_list?: string[];
        /**
         * IP of the control node
         */
        owner?: string;
        /**
         * Log path
         */
        path?: string;
        /**
         * Collection progress
         */
        progress?: string;
        /**
         * Log size
         */
        size?: string;
        /**
         * Start time of a log
         */
        start_timestamp?: string;
        /**
         * State
         */
        status?: "successful" | "failed";
        /**
         * ID of collection task
         */
        task_uuid?: string;
        groups?: string[];
        services?: string[];
      }[];
    };
    collectLogs: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * IP of the control node
         */
        log_owner?: string;
        /**
         * ID of collection task
         */
        task_uuid?: string;
      };
    };
    getLogServiceConfig: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Group name
         */
        group_name?: string;
        /**
         * Service config list
         */
        service_list?: {
          /**
           * Name of service config list item
           */
          name?: string;
          /**
           * Path list of service config list item
           */
          path?: string[];
        }[];
      }[];
    };
    getHostNics: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Bonding info
         */
        bonding_detail?: string;
        /**
         * Not in use for now
         */
        bonding_master?: string;
        /**
         * Bonding mode
         */
        bonding_mode?: string;
        /**
         * Gateway
         */
        gateway?: string;
        /**
         * MAC address
         */
        hwaddr?: string;
        /**
         * IP address
         */
        ipaddr?: string;
        /**
         * Whether this is a physical NIC
         */
        is_physical?: boolean;
        /**
         * MTU
         */
        mtu?: number;
        /**
         * Name
         */
        name?: string;
        /**
         * Mask
         */
        netmask?: string;
        /**
         * Whether it is running
         */
        running?: boolean;
        /**
         * Speed
         */
        speed?: number;
        /**
         * Whether the NIC is up
         */
        up?: boolean;
        /**
         * VLAN ID
         */
        vlan?: string;
        /**
         * Use
         */
        usage?: string;
      }[];
    };
    getClusterServices: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        data?: {
          /**
           * pid
           */
          current_pid?: number;
          /**
           * Execution path
           */
          exec_path?: string;
          /**
           * Last pid
           */
          last_pid?: number;
          pinfo?: {
            /**
             * Whether the service is running
             */
            is_running?: boolean;
            /**
             * Service process name
             */
            name?: string;
            /**
             * Service state
             */
            status?: string;
            /**
             * Uptime
             */
            uptime?: number;
            /**
             * User who runs this process
             */
            user?: string;
            /**
             * Role of this process
             */
            role?: string;
          };
          /**
           * Running state
           */
          running_state?: string;
          /**
           * Service name
           */
          service_name?: string;
          /**
           * Whether this service is auto-started
           */
          service_state?: string;
          /**
           * Duration in a state
           */
          state_duration?: string;
        }[];
        ec?: "EOK";
        error?: {};
        /**
         * Node hostname
         */
        host?: string;
        /**
         * Node management IP
         */
        management_ip?: string;
      }[];
    };
    getServiceInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * pid
         */
        current_pid?: number;
        /**
         * Execution path
         */
        exec_path?: string;
        /**
         * Last pid
         */
        last_pid?: number;
        pinfo?: {
          /**
           * Whether the service is running
           */
          is_running?: boolean;
          /**
           * Service process name
           */
          name?: string;
          /**
           * Service state
           */
          status?: string;
          /**
           * Uptime
           */
          uptime?: number;
          /**
           * User who runs this process
           */
          user?: string;
          /**
           * Role of this process
           */
          role?: string;
        };
        /**
         * Running state
         */
        running_state?: string;
        /**
         * Service name
         */
        service_name?: string;
        /**
         * Whether this service is auto-started
         */
        service_state?: string;
        /**
         * Duration in a state
         */
        state_duration?: string;
      };
    };
    getServicesInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * pid
         */
        current_pid?: number;
        /**
         * Execution path
         */
        exec_path?: string;
        /**
         * Last pid
         */
        last_pid?: number;
        pinfo?: {
          /**
           * Whether the service is running
           */
          is_running?: boolean;
          /**
           * Service process name
           */
          name?: string;
          /**
           * Service state
           */
          status?: string;
          /**
           * Uptime
           */
          uptime?: number;
          /**
           * User who runs this process
           */
          user?: string;
          /**
           * Role of this process
           */
          role?: string;
        };
        /**
         * Running state
         */
        running_state?: string;
        /**
         * Service name
         */
        service_name?: string;
        /**
         * Whether this service is auto-started
         */
        service_state?: string;
        /**
         * Duration in a state
         */
        state_duration?: string;
      }[];
    };
    getLicenseInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        license_capabilities?: {
          /**
           * Whether MetroX cluster is supported
           */
          has_metrox?: boolean;
          /**
           * Whether backup is supported
           */
          has_remote_backup?: boolean;
        };
        /**
         * Max node count
         */
        max_chunk_num?: number;
        /**
         * Max physical capacity
         */
        max_physical_space_size?: number;
        /**
         * Max physical capacity per node
         */
        max_physical_data_capacity?: number;
        /**
         * Max physical capacity per node
         */
        max_physical_data_capacity_per_node?: number;
        /**
         * Max datastore count
         */
        max_pool_num?: number;
        /**
         * Max snapshot count
         */
        max_snap_num?: number;
        /**
         * Max volume count
         */
        max_volume_num?: number;
        /**
         * Max volume size
         */
        max_volume_size?: number;
        /**
         * Validity period
         */
        period?: number;
        /**
         * Licence type
         */
        product_name?: string;
        /**
         * Serial number
         */
        serial?: string;
        /**
         * Date of sign-up
         */
        sign_date?: number;
        license_type?: string;
        software_edition?: string;
        /**
         * Date of maintenance
         */
        maintenance_start_date?: number;
        /**
         * maintenance period
         */
        maintenance_period?: number;
        /**
         * Date of subscription
         */
        subscription_start_date?: number;
        /**
         * subscription period
         */
        subscription_period?: number;
      };
    };
    putLicenseInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    parseLicenseInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        license_capabilities?: {
          /**
           * Whether MetroX cluster is supported
           */
          has_metrox?: boolean;
          /**
           * Whether backup is supported
           */
          has_remote_backup?: boolean;
        };
        /**
         * Max node count
         */
        max_chunk_num?: number;
        /**
         * Max physical capacity per node
         */
        max_physical_data_capacity?: number;
        /**
         * Max physical capacity per node
         */
        max_physical_data_capacity_per_node?: number;
        /**
         * Max physical capacity
         */
        max_physical_space_size?: number;
        /**
         * Max datastore count
         */
        max_pool_num?: number;
        /**
         * Max snapshot count
         */
        max_snap_num?: number;
        /**
         * Max volume count
         */
        max_volume_num?: number;
        /**
         * Max volume size
         */
        max_volume_size?: number;
        /**
         * Validity period
         */
        period?: number;
        /**
         * Licence type
         */
        product_name?: string;
        /**
         * Serial number
         */
        serial?: string;
        /**
         * Date of sign-up
         */
        sign_date?: number;
        license_type?: string;
        software_edition?: string;
        /**
         * Date of maintenance
         */
        maintenance_start_date?: number;
        /**
         * maintenance period
         */
        maintenance_period?: number;
        /**
         * Date of subscription
         */
        subscription_start_date?: number;
        /**
         * subscription period
         */
        subscription_period?: number;
      };
    };
    getClusterSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        cluster_id?: string;
        cluster_name?: string;
      };
    };
    putClusterSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        count?: number;
      };
    };
    getNTPSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * NTP mode
         */
        ntp_mode?: string;
        ntp_servers?: string[];
      };
    };
    putNTPSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    getDNSSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        dns_servers?: string[];
      };
    };
    putDNSSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    getVIPSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Management network VIP
         */
        management_vip?: string;
        /**
         * iSCSI service VIP
         */
        iscsi_vip?: string;
      };
    };
    putVIPSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        count?: number;
      };
    };
    putMGTSettings: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    getSSL: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Effective time
         */
        available_time?: number;
        /**
         * Expiry time
         */
        expire_time?: number;
        /**
         * Whether it is self-signed
         */
        is_self_signed?: boolean;
        /**
         * City where the certificate is issued
         */
        issuer_city?: string;
        /**
         * Name of the certificate authority
         */
        issuer_common_name?: string;
        /**
         * Country where the certificate is issued
         */
        issuer_country_code?: string;
        /**
         * Certificate authority's organization
         */
        issuer_organization_name?: string;
        /**
         * Name of certificate authority's organization
         */
        issuer_organization_unit?: string;
        /**
         * Province/state where the certificate authority is located
         */
        issuer_state?: string;
        /**
         * Certificate serial number
         */
        serial_number?: string;
        /**
         * Algorithm used by the certificate authority to sign certificates
         */
        sign_algorithm_name?: string;
        /**
         * City of the certificate owner
         */
        subject_city?: string;
        /**
         * Name of the certificate owner
         */
        subject_common_name?: string;
        /**
         * Country of the certificate owner
         */
        subject_country_code?: string;
        /**
         * Certificate owner's organization
         */
        subject_organization_name?: string;
        /**
         * Name of certificate owner's organization
         */
        subject_organization_unit?: string;
        /**
         * Province/state where the certificate owner lives
         */
        subject_state?: string;
      };
    };
    postSSL: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    uploadSSL: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    getTime: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        utc_time?: number;
      };
    };
    getTasks: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        migration?: {
          /**
           * Amount of data to be migrated
           */
          migrate_size?: number;
          /**
           * Migration speed
           */
          migrate_speed?: number;
        };
        node_status?: {
          /**
           * Count of hosts in connected state
           */
          connecting?: number;
          connecting_hosts?: string[];
          /**
           * Count of idle hosts
           */
          idle?: number;
          idle_hosts?: string[];
          /**
           * Count of hosts being removed
           */
          removing?: number;
          removing_hosts?: string[];
        };
        recovery?: {
          /**
           * Amount of data to be recovered
           */
          recover_size?: number;
          /**
           * Recovery speed
           */
          recover_speed?: number;
        };
      };
    };
    getRackTopos: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Child topo. For instance, the child topo of a rack is a brick
         */
        child_topos?: {};
        /**
         * Description
         */
        desc?: string;
        /**
         * Topo ID
         */
        id?: string;
        /**
         * Topo name
         */
        name?: string;
        /**
         * Parent topo's ID. For instance, the parent topo of a brick is a rack
         */
        parent_id?: string;
        /**
         * Topo type
         */
        type?: number;
      };
    };
    createTopo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Topo ID
         */
        id?: string;
        /**
         * Topo name
         */
        name?: string;
        /**
         * Parent topo's ID. For instance, the parent topo of a brick is a rack
         */
        parent_id?: string;
        position?: {
          column?: number;
          row?: number;
        };
        /**
         * Topo type. It can be one of following values CLUSTER, ZONE, RACK, BRICK, NODE.
         */
        type?: 1 | 2 | 3 | 4 | 5;
        dimension?: {
          column?: number;
          row?: number;
        };
        /**
         * Description
         */
        desc?: string;
        /**
         * Creation time
         */
        create_time?: number;
        /**
         * Child topo. For instance, the child topo of a rack is a brick
         */
        child_topos?: {}[];
        capaticy?: {
          column?: number;
          row?: number;
        };
      };
    };
    updateTopo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Topo ID
         */
        id?: string;
        /**
         * Topo name
         */
        name?: string;
        /**
         * Parent topo's ID. For instance, the parent topo of a brick is a rack
         */
        parent_id?: string;
        position?: {
          column?: number;
          row?: number;
        };
        /**
         * Topo type. It can be one of following values CLUSTER, ZONE, RACK, BRICK, NODE.
         */
        type?: 1 | 2 | 3 | 4 | 5;
        dimension?: {
          column?: number;
          row?: number;
        };
        /**
         * Description
         */
        desc?: string;
        /**
         * Creation time
         */
        create_time?: number;
        /**
         * Child topo. For instance, the child topo of a rack is a brick
         */
        child_topos?: {}[];
        capaticy?: {
          column?: number;
          row?: number;
        };
      };
    };
    deleteTopo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    getVCAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * vCenter IP
         */
        host?: string;
        /**
         * Whether it is valid
         */
        is_valid?: boolean;
        /**
         * Port
         */
        port?: number;
        /**
         * Username
         */
        user?: string;
      };
    };
    postVCAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * vCenter IP
         */
        host?: string;
        /**
         * Whether it is valid
         */
        is_valid?: boolean;
        /**
         * Port
         */
        port?: number;
        /**
         * Username
         */
        user?: string;
      };
    };
    putVCAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * vCenter IP
         */
        host?: string;
        /**
         * Whether it is valid
         */
        is_valid?: boolean;
        /**
         * Port
         */
        port?: number;
        /**
         * Username
         */
        user?: string;
      };
    };
    deleteVCAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    };
    getVCAssociated: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        esxi_associated?: string;
        port?: number;
      };
    };
    getVSSummary: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        cpu_usage_in_cluster?: number;
        hz?: number;
        memory_usage_in_cluster?: number;
        provisioned_cpu_cores?: number;
        provisioned_cpu_cores_for_active_vm?: number;
        provisioned_memory_in_byte?: number;
        provisioned_memory_in_byte_for_active_vm?: number;
        total_cpu_cores?: number;
        total_memory_in_byte?: number;
        total_vms?: number;
        vm_state?: {
          poweredOff?: number;
          poweredOn?: number;
          suspended?: number;
        };
        zone_summary?: {
          topo_id?: {
            /**
             * Cluster CPU usage (%)
             */
            cpu_usage_in_cluster?: number;
            /**
             * Cluster total CPU (in Hertz)
             */
            hz?: number;
            /**
             * Cluster memory usage (%)
             */
            memory_usage_in_cluster?: number;
            /**
             * Core count of provisioned CPUs
             */
            provisioned_cpu_cores?: number;
            /**
             * Core count of CPUs provisioned to running VMs
             */
            provisioned_cpu_cores_for_active_vm?: number;
            /**
             * Provisioned memory
             */
            provisioned_memory_in_byte?: number;
            /**
             * Memory provisioned to running VMs
             */
            provisioned_memory_in_byte_for_active_vm?: number;
            /**
             * Total CPU core count
             */
            total_cpu_cores?: number;
            /**
             * Total memory size
             */
            total_memory_in_byte?: number;
            /**
             * Total VM count
             */
            total_vms?: number;
            vm_state?: {
              /**
               * Count of powered-off VMs
               */
              poweredOff?: number;
              /**
               * Count of powered-on VMs
               */
              poweredOn?: number;
              /**
               * Count of suspended VMs
               */
              suspended?: number;
            };
          };
        };
      };
    };
    getDataStore: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: string[];
    };
    getAllDataStore: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        datastore_name?: string[];
      };
    };
    getSpecificVSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      };
    };
    updateVSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      }[];
    };
    deleteVSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    getAllVSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      }[];
    };
    createVSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      }[];
    };
    updateManyVSAccounts: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        success?: {
          /**
           * Node UUID
           */
          host_uuid?: string;
          /**
           * Node hostname
           */
          host_name?: string;
          /**
           * Hypervisor IP associated with the node
           */
          host?: string;
          /**
           * Account associated with the node
           */
          user?: string;
          /**
           * Whether the account associated with the node is valid
           */
          is_valid?: boolean;
          /**
           * Port associated with the node
           */
          port?: number;
        }[];
        failure?: {
          /**
           * Node UUID
           */
          host_uuid?: string;
          /**
           * Node hostname
           */
          host_name?: string;
          /**
           * Hypervisor IP associated with the node
           */
          host?: string;
          /**
           * Account associated with the node
           */
          user?: string;
          /**
           * Whether the account associated with the node is valid
           */
          is_valid?: boolean;
          /**
           * Port associated with the node
           */
          port?: number;
        }[];
      };
    };
    getAvailableHosts: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        host?: string;
        host_uuid?: string;
        is_valid?: boolean;
      }[];
    };
    getXSSummary: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        cpu_usage_in_cluster?: number;
        hz?: number;
        memory_usage_in_cluster?: number;
        provisioned_cpu_cores?: number;
        provisioned_cpu_cores_for_active_vm?: number;
        provisioned_memory_in_byte?: number;
        provisioned_memory_in_byte_for_active_vm?: number;
        total_cpu_cores?: number;
        total_memory_in_byte?: number;
        total_vms?: number;
        vm_state?: {
          poweredOff?: number;
          poweredOn?: number;
          suspended?: number;
        };
        zone_summary?: {
          topo_id?: {
            /**
             * Cluster CPU usage (%)
             */
            cpu_usage_in_cluster?: number;
            /**
             * Cluster total CPU (in Hertz)
             */
            hz?: number;
            /**
             * Cluster memory usage (%)
             */
            memory_usage_in_cluster?: number;
            /**
             * Core count of provisioned CPUs
             */
            provisioned_cpu_cores?: number;
            /**
             * Core count of CPUs provisioned to running VMs
             */
            provisioned_cpu_cores_for_active_vm?: number;
            /**
             * Provisioned memory
             */
            provisioned_memory_in_byte?: number;
            /**
             * Memory provisioned to running VMs
             */
            provisioned_memory_in_byte_for_active_vm?: number;
            /**
             * Total CPU core count
             */
            total_cpu_cores?: number;
            /**
             * Total memory size
             */
            total_memory_in_byte?: number;
            /**
             * Total VM count
             */
            total_vms?: number;
            vm_state?: {
              /**
               * Count of powered-off VMs
               */
              poweredOff?: number;
              /**
               * Count of powered-on VMs
               */
              poweredOn?: number;
              /**
               * Count of suspended VMs
               */
              suspended?: number;
            };
          };
        };
      };
    };
    getXSDataStore: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        hosts?: {
          /**
           * Mount address
           */
          address?: string;
          device_config?: {
            /**
             * Mount options
             */
            options?: string;
            /**
             * IP of the node on which the datastore is mounted
             */
            server?: string;
            /**
             * Mount path
             */
            serverpath?: string;
          };
          /**
           * Hostname of the node on which the datastore is mounted
           */
          hostname?: string;
        }[];
        /**
         * Description of SR name
         */
        name_description?: string;
        /**
         * Resource label
         */
        name_label?: string;
        /**
         * Physical capacity
         */
        physical_size?: string;
        /**
         * Node UUID
         */
        uuid?: string;
      };
    };
    getAllXSDataStore: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        hosts?: {
          /**
           * Mount address
           */
          address?: string;
          device_config?: {
            /**
             * Mount options
             */
            options?: string;
            /**
             * IP of the node on which the datastore is mounted
             */
            server?: string;
            /**
             * Mount path
             */
            serverpath?: string;
          };
          /**
           * Hostname of the node on which the datastore is mounted
           */
          hostname?: string;
        }[];
        /**
         * Description of SR name
         */
        name_description?: string;
        /**
         * Resource label
         */
        name_label?: string;
        /**
         * Physical capacity
         */
        physical_size?: string;
        /**
         * Node UUID
         */
        uuid?: string;
      }[];
    };
    getSpecificXSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      };
    };
    updateXSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      }[];
    };
    deleteXSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {};
    };
    getAllXSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      }[];
    };
    createXSAccount: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * Node UUID
         */
        host_uuid?: string;
        /**
         * Node hostname
         */
        host_name?: string;
        /**
         * Hypervisor IP associated with the node
         */
        host?: string;
        /**
         * Account associated with the node
         */
        user?: string;
        /**
         * Whether the account associated with the node is valid
         */
        is_valid?: boolean;
        /**
         * Port associated with the node
         */
        port?: number;
      }[];
    };
    updateManyXSAccounts: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        success?: {
          /**
           * Node UUID
           */
          host_uuid?: string;
          /**
           * Node hostname
           */
          host_name?: string;
          /**
           * Hypervisor IP associated with the node
           */
          host?: string;
          /**
           * Account associated with the node
           */
          user?: string;
          /**
           * Whether the account associated with the node is valid
           */
          is_valid?: boolean;
          /**
           * Port associated with the node
           */
          port?: number;
        }[];
        failure?: {
          /**
           * Node UUID
           */
          host_uuid?: string;
          /**
           * Node hostname
           */
          host_name?: string;
          /**
           * Hypervisor IP associated with the node
           */
          host?: string;
          /**
           * Account associated with the node
           */
          user?: string;
          /**
           * Whether the account associated with the node is valid
           */
          is_valid?: boolean;
          /**
           * Port associated with the node
           */
          port?: number;
        }[];
      };
    };
    getAvailableXSHosts: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        host?: string;
        host_uuid?: string;
        is_valid?: boolean;
      }[];
    };
    updateUpgradeClusterTool: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * UUID
         */
        uuid?: string;
        /**
         * start time of updating process
         */
        start_timestamp?: string;
        /**
         * end time of updating process
         */
        end_timestamp?: string;
        /**
         * status of updating process
         */
        status?: string;
        /**
         * the name of iso file
         */
        iso?: string;
        /**
         * the name of iso meta file
         */
        metadata?: string;
        upgrade_progress?: {
          /**
           * the current step of updating process
           */
          current_step?: number;
          /**
           * total steps of updating process
           */
          total_step?: number;
          /**
           * the current stage of updating process
           */
          stage?: string;
          /**
           * finished stages of updating process
           */
          finished_stage?: string[];
        };
      };
    };
    getUpgradeClusterToolsStatus: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * UUID
         */
        uuid?: string;
        /**
         * start time of updating process
         */
        start_timestamp?: string;
        /**
         * end time of updating process
         */
        end_timestamp?: string;
        /**
         * status of updating process
         */
        status?: string;
        /**
         * the name of iso file
         */
        iso?: string;
        /**
         * the name of iso meta file
         */
        metadata?: string;
        upgrade_progress?: {
          /**
           * the current step of updating process
           */
          current_step?: number;
          /**
           * total steps of updating process
           */
          total_step?: number;
          /**
           * the current stage of updating process
           */
          stage?: string;
          /**
           * finished stages of updating process
           */
          finished_stage?: string[];
        };
      };
    };
    getUpgradingClusterToolsVersion: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * main version of tool
         */
        main_version?: string;
        /**
         * release version of tool
         */
        release_version?: string;
      };
    };
    getMaintenanceJobInfo: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        current_state?: "enter" | "exit";
        enter?: {
          cancel_flag?: boolean;
          cancel_support?: boolean;
          start_time?: number;
          end_time?: number;
          state?: "pending" | "processing" | "done" | "failed" | "canceled";
          vm_operate_record_uuid?: string;
          stages?: {
            name?: string;
            state?: "pending" | "processing" | "done" | "failed" | "canceled";
            details?: {
              operated_time: number;
              source_host_ip: string;
              state: "pending" | "processing" | "done" | "failed" | "canceled";
              target_host_ip?: string;
              source_host_name?: string;
              target_host_name?: string;
              vm_ha: boolean;
              vm_name?: string;
              vm_state?: "running" | "stopped";
              vm_uuid: string;
              verify?: {
                changed?: boolean;
                reason?: string;
              };
            }[];
          }[];
        };
        exit?: {
          cancel_flag?: boolean;
          cancel_support?: boolean;
          start_time?: number;
          end_time?: number;
          state?: "pending" | "processing" | "done" | "failed" | "canceled";
          vm_operate_record_uuid?: string;
          stages?: {
            name?: string;
            state?: "pending" | "processing" | "done" | "failed" | "canceled";
            details?: {
              operated_time: number;
              source_host_ip: string;
              state: "pending" | "processing" | "done" | "failed" | "canceled";
              target_host_ip?: string;
              source_host_name?: string;
              target_host_name?: string;
              vm_ha: boolean;
              vm_name?: string;
              vm_state?: "running" | "stopped";
              vm_uuid: string;
              verify?: {
                changed?: boolean;
                reason?: string;
              };
            }[];
          }[];
        };
        host_uuid?: string;
        uuid?: string;
      };
    };
    enterPreCheck: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    enterMaintenance: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    exitPreCheck: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: any;
    };
    exitMaintenance: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        /**
         * job id
         */
        job_id?: string;
      };
    };
    cancelMaintenanceJob: {
      data?: {};
      ec?: "EOK";
      error?: {};
    } & {
      data?: {
        cancel_result?: boolean;
      };
    };
  };
}
