import ejs from "ejs";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import camelCase from "camelcase";
import prettier from "prettier";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const warningMsg = `/**
* This file is generated by the ejs template, 
* Please do not modify this file directly to 
* avoid being overwritten by the automatic generation process.
* Take look as packages/eagle/tools/genHtmlEvent.mts.
*/`;

const generate = async () => {
  const components = [
    {
      name: "Button",
      events: ["Click", "DoubleClick", "MouseEnter",],
    },
  ];

  components.forEach(async (component) => {
    const result = await ejs.renderFile(
      path.resolve(__dirname, "./templates/htmlEvent.test.ejs"),
      {
        events: component.events,
        component: component.name,
        camelCase,
      }
    );

    const script = prettier.format(result, {
      parser: "typescript",
      useTabs: false,
      tabWidth: 2,
      endOfLine: "lf",
    });

    fs.mkdirSync(
      path.resolve(__dirname, `../src/components/${component.name}/__test__`),
      {
        recursive: true,
      }
    );

    fs.writeFileSync(
      path.resolve(
        __dirname,
        `../src/components/${component.name}/__test__/htmlEvent.test.tsx`
      ),
      warningMsg + "\n" + script
    );
  });
};

Promise.resolve(generate());
