name: "Bundlewatch GitHub Action - on Tracked Branches Push"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install deps
        run: yarn install --frozen-lockfile
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: yarn build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}