name: "CI Check"

on:
  pull_request:
    branches: 
      - '**'

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label-check:
    runs-on: [self-hosted, linux]
    name: Check PR Label
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "feat, fix, chore, breaking change, refactor, enhancement, doc, storybook"
          pull-request-number: "${{ github.event.pull_request.number }}"

  test:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        node: [16]
    name: Run Test on Node ${{ matrix.node }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
        timeout-minutes: 15
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test:ci
  storybook-staging:
    name: Setup Storybook Staging
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        node: [16]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Set alias-domains variable
        id: set-alias-domains
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "next" ]; then
            echo "alias-domains=next-cloudtower-ui-kit.vercel.app" >> $GITHUB_ENV
          else
            echo "alias-domains=" >> $GITHUB_ENV
      - name: Set Up Storybook Staging
        uses: amondnet/vercel-action@v20
        id: vercel-action-staging
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: ${{ env.alias-domains }}
