name: publish
on:
  # When Release Pull Request is merged
  pull_request:
    branches:
      - main
      - next
      - v4.4
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        node: [16]
    name: Publish on Node ${{ matrix.node }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install deps
        run: yarn install --frozen-lockfile
        timeout-minutes: 15
      - name: Build
        run: yarn build
      - name: Copy Readme
        run: |
          cp ./README.md packages/eagle/README.md
      - name: Write .npmrc
        env:
          NPM_TOKEN: ${{ secrets.QINGHUA_CUI_SMARTX_NPM_TOKEN }}
        run: |
          echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      - name: Set Current Version
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Tag Check
        id: tag_check
        run: |
          GET_API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/v${CURRENT_VERSION}"
          http_status_code=$(curl -LI $GET_API_URL -o /dev/null -w '%{http_code}\n' -s \
            -H "Authorization: token ${GITHUB_TOKEN}")
          if [ "$http_status_code" -ne "404" ] ; then
            echo "::set-output name=exists_tag::true"
          else
            echo "::set-output name=exists_tag::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Git Tag
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.CURRENT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
      - name: Publish
        uses: nick-fields/retry@v2
        if: steps.tag_check.outputs.exists_tag == 'false'
        with:
          timeout_minutes: 10  # 设置超时时间，单位为分钟
          max_attempts: 3  # 设置最大重试次数
          command: |
            yarn lerna publish from-package --no-verify-access --yes
      - name: sync cnpm
        if: steps.tag_check.outputs.exists_tag == 'false'
        run: curl --location --request PUT 'http://192.168.26.29:7002/sync/@cloudtower/eagle?sync_upstream=true'
      - name: Get Output
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: dawidd6/action-download-artifact@v6
        with:
          name: publish-output-v${{ env.CURRENT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: create-publish-pr.yml
          workflow_conclusion: success
      - name: Read the output
        if: steps.tag_check.outputs.exists_tag == 'false'
        run: |
          echo "SLACK_USER=$(cat output.txt)" >> $GITHUB_ENV
      - name: Send to Slack
        if: steps.tag_check.outputs.exists_tag == 'false'
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          link_names: 1
          payload: |
            {
              "text": "Get New Version At ${{ env.CURRENT_VERSION }} <http://192.168.26.29:7002/package/@cloudtower/eagle|${{ env.CURRENT_VERSION }}> <@${{ env.SLACK_USER }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Build Changelog
        id: github_release
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feat"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix"]
                },
                {
                    "title": "## 🧪 Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## 💬 Other",
                    "labels": ["other", "chore"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean .npmrc
        if: always()
        run: rm ~/.npmrc
