name: publish

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    name: Test on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install deps
        run: yarn install --frozen-lockfile
        timeout-minutes: 3
      - name: Test
        run: cd packages/eagle && yarn run test:ci

  publish:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    name: Publish on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install deps
        run: yarn install --frozen-lockfile
        timeout-minutes: 3
      - name: Build
        run: yarn build
      - name: Copy Readme
        run: |
          cp ./README.md packages/eagle/README.md
      - name: Write .npmrc
        env:
          NPM_TOKEN: ${{ secrets.QINGHUA_CUI_SMARTX_NPM_TOKEN }}
        run: |
          echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      - name: Publish
        run: |
          yarn lerna publish from-git --no-verify-access --yes
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feat"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix"]
                },
                {
                    "title": "## 🧪 Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## 💬 Other",
                    "labels": ["other", "chore"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean .npmrc
        if: always()
        run: rm ~/.npmrc
