name: storybook

on:
  push:
    branches: ["main", "next"]

jobs:
  storybook-deploy:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Deploy Storybook
        uses: ./.github/actions/deploy-storybook
        with:
          branch-name: ${{ github.ref_name }}
          comment-pr: 'false'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}

