name: storybook

on:
  push:
    branches: ["main"]

jobs:
  storybook-production:
    name: Storybook Production
    runs-on: [self-hosted, linux]
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: Set Up Storybook Production
        uses: amondnet/vercel-action@v20
        id: vercel-action-production
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
